-- 코드를 입력하세요
SELECT * FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID WHERE CATEGORY = '경제' ORDER BY PUBLISHED_DATE;

SELECT BOOK_ID, AUTHOR_NAME, date_format(PUBLISHED_DATE, '%Y-%m-%d') FROM BOOK JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID WHERE CATEGORY = '경제' ORDER BY PUBLISHED_DATE;